# Generated by Django 4.1.3 on 2022-12-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('unit', models.CharField(max_length=5, verbose_name='Unit')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Weight',
                'verbose_name_plural': 'Weights',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN code')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('make', models.CharField(max_length=20, verbose_name='Make')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('dimension', models.JSONField(verbose_name='Dimension')),
                ('weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.weight')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
